### ISSUE TITLE
Update to CIS Docker 1.12.0 Benchmark

### ISSUE THREAD

**Issue by atomic111** [dev-sec/cis-docker-benchmark#11]

**Comment by EtienneK** [comment]
Is this being looked at?

**Comment by chris-rock** [comment]
Yes, PRs are welcome

**Comment by atomic111** [comment]
https://benchmarks.cisecurity.org/tools2/docker/CIS_Docker_1.12.0_Benchmark_v1.0.0.pdf

**Comment by atomic111** [comment]
the pr #19 updates the controls 1.1 to 2.16. we need a additional pr to update the rest

**Comment by chris-rock** [comment]
Most of CIS Benchmark 1.12 is implemented now. We are missing 9 scored controls now:
 * 2.16, 2.17, 2.18
 * 4.6, 4.7 (not scored), 4.8 (not scored), 4.9 (not scored), 4.10 (not scored)
 * 5.26, 5.27, 5.28, 5.29 (not scored), 5.30, 5.31
