### ISSUE TITLE
docker variable not defined

### ISSUE THREAD

**Issue by kidbrax** [dev-sec/cis-docker-benchmark#31]
I keep getting this error:

```
/usr/local/bundle/gems/rspec-expectations-3.5.0/lib/rspec/matchers.rb:967:in `method_missing': undefined local variable or method `docker' for #<#<Class:0x00000003203a70>:0x000000031c9fa0> (NameError)
	from cis-docker-benchmark-master/controls/container_images.rb:50:in `block in load_with_context'
```

On [line 50](https://github.com/dev-sec/cis-docker-benchmark/blob/master/controls/container_images.rb#L50), I don't see where it is defined either.  Should that be getting set somewhere beforehand?

**Comment by chris-rock** [comment]
Version 1.3 of this benchmark requires at least InSpec 1.21.0, see
https://github.com/dev-sec/cis-docker-benchmark#requirements
