### ISSUE TITLE
Wrong placement of flag in command

### ISSUE THREAD

**Issue by nnickie23** [dev-sec/cis-docker-benchmark#72]
**Describe the bug**
`controls/container_images.rb` uses `docker history` to inspect commands, and the command looks like this: 
```
command("docker --no-trunc history #{id}| grep -e 'update'")
```

**Expected behavior**
The output without error is expected. This can be achieved by placing the flag `---no-trunc` at the end of command string:
```
command("docker history #{id} --no-trunc | grep -e 'update'")
```

**Actual behavior**
The stdout of running this command is empty because the command has an error:
```
unknown flag: --no-trunc
...
```

**Example code**

```
command(docker --no-trunc history #{id}| grep -e 'update')
```

**OS / Environment**

NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"

**Inspec Version**

```paste below
4.46.13

```

**Baseline Version**

```paste below
1.12.0
```

**Comment by rndmh3ro** [comment]
Thanks for reporting this! Do you want to create a PR to fix it?

**Comment by nnickie23** [comment]
@rndmh3ro yes

**Comment by nnickie23** [comment]
How could I do this?

**Comment by rndmh3ro** [comment]
Take a look at the docs here: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
